<?php
/** @var $block */ ?>

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="name"><span><?= $block->
                                    escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>

                        <div class="field email required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>

                        <div class="field contact required">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Contact')) ?></span></label>
                            <div class="control">
                                <input name="contact" id="contact" title="Contact" value="" class="input-text"
                                       type="text">
                            </div>
                        </div>

                        <div class="field message required">
                            <label class="label" for="message">
                                <span><?= $block->escapeHtml(__('Enter your message here!')) ?></span>
                            </label>
                            <div class="control">
                          <textarea name="comment"
                          id="comment"
                          title="<?= $block->escapeHtmlAttr(__('Enter your message here!')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"></textarea>
                            </div>
                        </div>

                        <div class="field created_at required">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('CreatedAt')) ?></span></label>
                            <div class="control">
                                <input name="created_at" id="created_at" title="Created At" value="" class="input-text"
                                       type="text">
                            </div>
                        </div>

                        <div class="field updated_at required">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('UpdatedAt')) ?></span></label>
                            <div class="control">
                                <input name="updated_at" id="updated_at" title="Updated At" value="" class="input-text"
                                       type="text">
                            </div>
                        </div>

                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save">
                        <span><?= $block->
                            escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
